### ISSUE TITLE
Duplicated v0.2 

### ISSUE THREAD

**Issue by SimonMarquis** [martinbonnin/xoxo#9]
It seems you released the v0.2 twice: https://github.com/martinbonnin/Xoxo/releases/tag/v0.2
Shouldn't it be a v0.3 instead?

**Comment by martinbonnin** [comment]
You are 100% right. Sorry about this, that's what I get for forgetting to update the build files after a release... I just added a [small script ](https://github.com/martinbonnin/Xoxo/blob/main/scripts/tag.main.kts)to make sure that doesn't happen again. 0.3 is just out on Maven Central, I'll update the Github releases accordingly.
